from .generators.colors import ColorGenerator
from .generators.spacing import SpacingGenerator
from .generators.typography import TypographyGenerator
from .generators.layout import LayoutGenerator
from .generators.borders import BordersGenerator
from .generators.effects import EffectsGenerator

def generate_utilities(config):
    """Generate SCSS utilities based on configuration using OOP generators."""
    
    scss = []
    scss.append("// Generated by TailPySCSS")
    scss.append("")

    # List of generator classes to instantiate and run
    generator_classes = [
        ColorGenerator,
        SpacingGenerator,
        TypographyGenerator,
        LayoutGenerator,
        BordersGenerator,
        EffectsGenerator
    ]

    for gen_class in generator_classes:
        generator = gen_class(config)
        scss.append(generator.generate())
        scss.append("")

    return "\n".join(scss)

