from .generators.colors import ColorGenerator
from .generators.spacing import SpacingGenerator
from .generators.typography import TypographyGenerator
from .generators.layout import LayoutGenerator
from .generators.borders import BordersGenerator
from .generators.effects import EffectsGenerator

def generate_utilities(config, active_contexts=None):
    """
    Generate SCSS utilities based on configuration.
    
    Args:
        config (dict): The loaded configuration.
        active_contexts (set): List of detected UI contexts (e.g. {'card', 'navbar'}).
    """
    
    scss = []
    scss.append("// Generated by TailPySCSS")
    scss.append("")

    # --- NEW: Vibe Engine Injection ---
    from tailpyscss.vibes import VIBE_PRESETS
    
    # Get active vibe from config, default to 'flat'
    active_vibe_name = config.get("vibe", "flat")
    vibe_vars = VIBE_PRESETS.get(active_vibe_name, VIBE_PRESETS["flat"]) 
    
    scss.append(f"// --- Active Vibe: {active_vibe_name.upper()} ---")
    for var, val in vibe_vars.items():
        scss.append(f"${var}: {val};")
    scss.append("")

    # 1. Global Utilities (Always Included)
    generator_classes = [
        ColorGenerator,
        SpacingGenerator,
        TypographyGenerator,
        LayoutGenerator,
        BordersGenerator,
        EffectsGenerator
    ]

    for gen_class in generator_classes:
        generator = gen_class(config)
        scss.append(generator.generate())
        scss.append("")

    # 2. Context-Aware Components (Tree Shaken)
    if active_contexts:
        scss.append("// --- Active Contexts (Tree Shaken) ---")
        for context in sorted(list(active_contexts)):
            # This generates: @import "components/card";
            # builder.py will detect this import and fetch it from internal_assets if not in user folder
            scss.append(f'@import "components/{context}";')
        scss.append("")

    return "\n".join(scss)

