import json

def generate_theme_bridge(config):
    """
    Generates a Python module (tailpyscss_theme.py) that exposes the 
    configuration (colors, spacing, etc.) to the backend code.
    """
    content = f"""# Auto-generated by TailPySCSS. Do not edit.
# Use this to access your design tokens in Python code (Flask/Django views).

THEME = {json.dumps(config, indent=4)}

COLORS = THEME.get('colors', {{}})
SPACING = THEME.get('spacing', {{}})
SCREENS = THEME.get('screens', {{}})
"""
    
    with open("tailpyscss_theme.py", "w") as f:
        f.write(content)
